site_name: My Docs
site_url: https://devopsdunkin.github.io/terraform-propvider-nagios
repo_url: https://github.com/devopsdunkin/terraform-provider-nagios
theme: readthedocs
nav:
  - Home: index.md
  - Resources:
    - resource_hostgroup: resource_hostgroup.md