version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.6
      - image: devopsdunkin/nagiosxi:ci-tests
    working_directory: /go/src/github.com/devopsdunkin/terraform-provider-nagios
    steps:
      - checkout
      - run: go mod download
      - save_cache:
          key: go-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          command: |
            go test -v ./nagios
    environment:
      GO111MODULE: "on"

  release:
    docker:
      - image: circleci/golang:1.12.6
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: build and release
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "devopsdunkin"]; then
              gox -os="linux darwin windows" -arch="amd64" -output="dist/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}"
              cd dist/ && gzip *
              if [ "$CIRCLE_TAG" ]; then
                  ghr -t $GITHUB_TOKEN -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --replace $CIRCLE_TAG dist/
              else
                echo "no tagged version to deploy"
              fi
            else
              echo "Release does not occur on forked master branch"
            fi
    environment:
      GO111MODULE: "on"

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
              ignore:
                - gh-pages
      - release:
          requires:
            - test
          filters:
            branches:
              only: devopsdunkin/master
            tags:
              only: /^v.*/