# Golang CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - image: devopsdunkin/docker-nagiosxi:ci-tests
    working_directory: /go/src/github.com/devopsdunkin/terraform-provider-nagios
    steps:
      - checkout
      - run: go mod download
      - save_cache:
          key: go-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          command: |
            go test -v ./nagios